### PR TITLE
Remove traces of multi-performance rate strata

### PR DESCRIPTION
**Pull request by saquino0827**
Received confirmation from the measures team via Sarah White:
    -CMS347v1 is a single performance rate and does not require strata. I have removed the strata from the measure data.

### CODE REVIEW

**Comment by kalvinwang** [comment]
Thanks @saquino0827! Could you please bump the version number in package.json per the release instructions in [CONTRIBUTING.md](https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md)? I think bumping it by 0.0.1 makes sense for this change since it's small.

**Comment by kalvinwang** [comment]
@saquino0827 sorry I missed your comment-- I can go ahead and publish it once you merge this PR. It sounds like we'd like to set up an auto-publish-on-merge job soon anyway.

**Comment by rockykitamura** [comment]
@saquino0827 Can you resolve the merge conflict and merge this in?

**Comment by saquino0827** [comment]
Will resolve and merge this after my meetings. Thanks all.

**Pull request merged**
