### PR TITLE
Measure 268 missing exclusion code

### PR DESCRIPTION
**Pull request by jared-baker**
* Initial commit,  adding missing exclusion to csv, and output of generating json.

- Note I did not commit the new final single source output because it may have deltas due
  to logic changes in this repo which the services team does not manage.

#### Motivation for change

Backfilling reference data for claims to quality based on updated single source definition for 2019

#### What is being changed

Additional exclusion code being added for measure 268

#### Release checklist:
Tasks that must be done prior to merging this PR, including testing.

* [ ] [Package version updated](https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md#versioning-publishing-and-creating-new-releases)
* [ ] Documentation updated
* [ ] Unit tests added/passing
* [x] Verified working locally

##### Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPA-1663

### CODE REVIEW

**Comment by joshboley** [comment]
@jared-baker @mike-sanderson can you please elaborate on this PR?  The ticket in the description is an old ticket.  Wondering where this request came from.  Also, you have to be sure to bump the version if you want a new release before merging.

**Comment by jheltonsb** [comment]
@jared-baker looks like you linked the wrong ticket

**Comment by jheltonsb** [comment]
> @jared-baker @mike-sanderson can you please elaborate on this PR? The ticket in the description is an old ticket. Wondering where this request came from. Also, you have to be sure to bump the version if you want a new release before merging.
@joshboley The single source specs file given to use by Mathematica had an exclusion code missing from measure 268. We are needing to add this exclusion code to the measures data as well as the single source csv for this year

**Comment by jared-baker** [comment]
My mistake the PR header had a template and I must have glazed over the A in the ticket link. It has been corrected to point to our board.

**Comment by joshboley** [comment]
Ok, thank you!

**Comment by joshboley** [comment]
@jared-baker did you verify unit tests locally?  Please make another PR updating the package version and verifying unit tests.

**Comment by jheltonsb** [comment]
@jared-baker you shouldnt have merged this PR yet. Next time make sure the above happens before merging, please. Also, wait for most everyone to approve

**Pull request merged**
