### PR TITLE
[QPPA-1706] Correct 2017 QCDR Measures

### PR DESCRIPTION
**Pull request by lamroger**
I updated `util/measures/qcdr-measures.csv` with the changes specified in the changelog xlsx file attached to the ticket and ran `npm run build:measures` to regenerate the `measures-data.json`.

### CODE REVIEW

**Comment by lamroger** [comment]
My editor deleted trailing whitespaces in the descriptions... Is that okay?
Some people could be relying on it for displaying on a frontend.

**Comment by kalvinwang** [comment]
* you'll want to bump the package.json version number so might as well do it in this PR! instructions here: https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md#versioning-publishing-and-creating-new-releases
* just checking, did you run the associated tests?
* can you add the preprocessing steps you needed to do, that'll still be relevant next time, to contributing.md or wherever appropriate?
* deleting trailing whitespaces seems fine to me!
* bonus: if you can update contributing.md so it's less confusing, that would be awesome :)

**Comment by kencheeto** [comment]
we should preference _not_ changing these descriptions if possible:

* we don't know how people are depending on them
* other people ingesting these changes may/may not have the same editor setting, generally best to not modify upstream data (churn when someone else ingests these changes and reintroduces trailing spaces, for example)

but it's probably OK to leave as-is if it's a pain to revert them.

**Comment by lamroger** [comment]
@kalvinwang:
1. Sounds good, I'll bump the version in the PR and follow the rest of the publishing steps after merging.
2. Didnt run the tests earlier but ran `npm test` now and everything passed. I think `npm run build:measures` does some integrity checks too and GH/Jenkins runs `npm test`?
3/5. Yep, Sarah's helping with additional changes from ~above~ so I have time to edit docs.

@kencheeto:
1/2: Totally agree. I'd ask someone else to change back too...

**Comment by lamroger** [comment]
Confirmed changes in v8 change log are in qcdr-measures.csv.

Most of the changes are to denominator exclusion and other columns that are not visible in measures-data.json and to measures that are not from primary stewards so they're also not visible in measures-data.json.

@kencheeto / @kalvinwang could I get another review today and I'll merge, bump release version, and incorporate into qpp-submissions-api.

**Comment by kencheeto** [comment]
lmk if you need an additional review, if not then lgtm

**Pull request merged**
